### ISSUE TITLE
Improve text legibility

### ISSUE THREAD

**Issue by alexcarpenter** [csstools/cssdb#29]
The text legibility is a bit dificult to read when using a `300` weight. 

Maybe bump it up to `400` to increase legibility and remove global letter-spacing setting?

![screen shot 2018-05-15 at 10 09 51 am](https://user-images.githubusercontent.com/825855/40062001-29cd5f80-5828-11e8-8d93-1c91a2a7bd98.jpg)

**Comment by jonathantneal** [comment]
Thank you for pointing this out. I saw a few areas that I could improve. Here is a list of changes:

- [x] increase font-weight for improved legibility
- [x] consider matching font-family of https://preset-env.cssdb.org/
- [x] resolve inaccessible color contrast ratios
- [x] use consecutive headings
- [x] provide more descriptive alt labels for the stage badges

Please let me know if you think this resolves your concern.

**Comment by alexcarpenter** [comment]
This does, thanks!
