### ISSUE TITLE
Media Query Ranges on stage 3

### ISSUE THREAD

**Issue by malyw** [csstools/cssdb#30]
[Stage 3 cssdb definition](https://cssdb.org/#staging-process) states the proposal should be "implemented by at least 2 recognized browser vendors, possibly behind a flag"- added a [quick test](https://codepen.io/malyw/pen/xjmQBg) but couldn't find working implementation/flags, do we have the working environments to point the community?

**Comment by jonathantneal** [comment]
Thanks for pointing this out, @malyw.

@frivoal, @TabAtkins, are you aware of any implementor interest in Media Features in a Range Context?

While this is a Candidate Recommendation, I believe you are right in that there is no support, even behind a flag.

Related issue on caniuse: https://github.com/Fyrd/caniuse/issues/3984

**Comment by frivoal** [comment]
I don't know of any (but if you find one, let me know).

So some of the criteria for stage 3 are fulfilled, but not all.
