### ISSUE TITLE
MDN docs

### ISSUE THREAD

**Issue by yepninja** [csstools/cssdb#32]
Let's add links to mdn doc for features. Specification usually is more difficult to read, especially for beginners. Also, it will be useful for [site](https://preset-env.cssdb.org/features)

**Comment by yepninja** [comment]
And of course, I can help with this task.

**Comment by jonathantneal** [comment]
I think this is a good idea. I find both the spec and the mdn docs very useful. I rarely get by on the spec alone.

**Comment by yepninja** [comment]
#34

**Comment by jonathantneal** [comment]
This will be resolved by #34.

**Comment by jonathantneal** [comment]
Resolved by #34
