### ISSUE TITLE
PostCSS on cssdb web

### ISSUE THREAD

**Issue by nucliweb** [csstools/cssdb#40]
### PostCSS on cssdb web

I think that is a good sample that we use PostCSS on cssdb web site's CSS 🤪.

I can be doing a refactor of current CSS file to a PostCSS environment with **PostCSS Preset Env** .

**Comment by jonathantneal** [comment]
Since this issue would best belong in that repo, I’m closing it here. 😄

**Comment by nucliweb** [comment]
Ok, but is not the same cssdb website and postcss-preset-env website, right?

**Comment by jonathantneal** [comment]
Oh right. Right. My bad. I’ll look into the most minimal simple solution possible for gh-pages.

**Comment by jonathantneal** [comment]
I just had a few minutes, so I posted the initial work here https://github.com/csstools/cssdb/tree/feature/pcss

**Comment by jonathantneal** [comment]
We also need proper links for Avenir Next and Source Code Pro. Or new fonts.
