### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by dmartinjs** [csstools/cssdb#51]
<img width="731" alt="website" src="https://user-images.githubusercontent.com/53537199/62837404-4f56ef80-bc6f-11e9-912a-13d75e72bbb8.png">

**Comment by jonathantneal** [comment]
That’s fascinating. I wonder if you are getting an older cache. I brought it down for an hour a few days ago, but it’s been up for me since. Mind trying a hard refresh?

**Comment by dmartinjs** [comment]
It's up now, I'm closing this issue.

**Comment by minusfive** [comment]
@jonathantneal is it down for good? I'm getting the same again.

**Comment by jonathantneal** [comment]
@minusfive, the website is up. I don’t know why you would be seeing the old page.

**Comment by minusfive** [comment]
> @minusfive, the website is up. I don’t know why you would be seeing the old page.

Weird, seems to be in-and-out, bunch of us tested at work on different devices.

**Comment by jonathantneal** [comment]
That is very concerning.

Here is how it works:
I setup this domain on DreamHost to exclusively use GitHub nameservers, and GitHub actually serves the site. Everything is done according to the instructions that are in unison between both sites.

What do you suppose the issue is? I think this is a big deal, because I have not touched the settings since this was first resolved.

**Comment by minusfive** [comment]
> That is very concerning.
> 
> Here is how it works:
> I setup this domain on DreamHost to exclusively use GitHub nameservers, and GitHub actually serves the site. Everything is done according to the instructions that are in unison between both sites.
> 
> What do you suppose the issue is? I think this is a big deal, because I have not touched the settings since this was first resolved.

Hmm… Wonder if it's got something to do with DH's DNS? I'd suggest transferring your domain to Google's Domains, and turn SSL on on your GH pages settings. I wouldn't trust DH for these types of things. Let me know if you'd like a hand.
