### ISSUE TITLE
Site down?

### ISSUE THREAD

**Issue by jenstornell** [csstools/cssdb#55]
>Site Not Found
>Well, this is awkward. The site you're looking for is not here.

**Comment by TheLastZombie** [comment]
Looks like it was just a temporary issue.

![image](https://user-images.githubusercontent.com/8181990/70045550-94a78000-15c4-11ea-85ea-dc85f11c604d.png)

**Comment by heyallan** [comment]
Site returns:
- Site is not secure
- Site Not Found

**Comment by coagmano** [comment]
Definitely down now.
Getting a self signed cert warning, followed by Dreamhost's Site Not Found page.

<img width="295" alt="Screen Shot 2020-08-30 at 10 37 49 am" src="https://user-images.githubusercontent.com/292857/91648618-dcecc380-eaac-11ea-927a-54aff0331115.png">

**Comment by shawn-yee** [comment]
site fail

**Comment by Antonio-Laguna** [comment]
Site up :)
