### ISSUE TITLE
Media Query Ranges supported in Firefox since 63

### ISSUE THREAD

**Issue by JakoD** [csstools/cssdb#57]
Since it was asked in #30 

Tested against https://codepen.io/jakod/pen/rNaLjGq
Firefox 63+: ✓
Chrome 78 and 80 (dev): ✗
Safari 13: ✗
Edge 18: ✗

**Comment by petamoriken** [comment]
`(width < 600px)` is supported, but `(600px < width)` and `(600px < width < 1000px)` is not supported in Firefox.

**Comment by Antonio-Laguna** [comment]
I've requested MDN to update their data: https://github.com/mdn/browser-compat-data/issues/14593

**Comment by romainmenke** [comment]
MDN data has been updated 🎉
