### ISSUE TITLE
:has() pseudo-class is not part of the live profile

### ISSUE THREAD

**Issue by petamoriken** [csstools/cssdb#59]
`:has()` pseudo-class is not part of the live profile in specification, so current `:has()` example is invalid.

https://github.com/csstools/cssdb/blob/d61beb5d6d9cd43cc076ba6b97328a94a6f14ad1/cssdb.json#L403

> The `:has()` pseudo-class takes a selector list as an argument. In the current specification `:has` is not marked as part of the live selector profile, which means it can not be used within stylesheets; only with functions like `document.querySelector()`.

https://developer.mozilla.org/en-US/docs/Web/CSS/:has
https://www.w3.org/TR/selectors-4/#profiles

**Comment by Antonio-Laguna** [comment]
The example is correct again :) 

At the moment Safari is implementing `:has` in CSS so we can now consider it "part of the live profile in specification".
