### ISSUE TITLE
Dark mode text illegible

### ISSUE THREAD

**Issue by brianmaierjr** [csstools/cssdb#74]
I found your great site today and noticed that some of the text in dark mode was illegible. I forked the project and took a stab at it but something is overwriting the styles you all have [here](https://github.com/csstools/cssdb/blob/97b887e0d2997de8cce273ff07be570f2ee82cf4/src/styles/style.css#L369-L372) and I can't quite get it...

Screenshot of the issue:
![Screen Shot 2022-01-13 at 1 11 00 PM](https://user-images.githubusercontent.com/2747377/149387578-e9fcf340-0e16-42b2-9f10-56f2d6f02a37.png)

**Comment by Antonio-Laguna** [comment]
@brianmaierjr thanks for opening this issue. Can you let me know which browser was this on? I've tested on Firefox, Chrome, Safari and Edge (all on Mac) and it looks like the image below

![Screenshot 2022-01-13 at 19 27 12](https://user-images.githubusercontent.com/946645/149387984-c936d70c-2a45-4709-996f-ec0bd8b2023a.png)

Would love to be able to reproduce this issue and get it fixed :)

**Comment by brianmaierjr** [comment]
@Antonio-Laguna 

Sure thing! Hope this helps. 

OS: macOS MOnterey Version 12.1
Chrome: Version 97.0.4692.71 (Official Build) (x86_64)

**Comment by Antonio-Laguna** [comment]
This is very odd :/ exactly same browser I have, will try other things

![Screenshot 2022-01-13 at 19 32 48](https://user-images.githubusercontent.com/946645/149388756-7330a40f-96d3-47c6-adda-e63e365e6d3e.png)

**Comment by brianmaierjr** [comment]
@Antonio-Laguna weird! I can see your styles in the inspector but it's clearly not working(see screenshot) 🤷🏻‍♂️ 

![Screen Shot 2022-01-13 at 1 36 31 PM](https://user-images.githubusercontent.com/2747377/149389399-cc4aef1b-ee92-488d-b070-b99e44d01aa4.png)

**Comment by Antonio-Laguna** [comment]
Going to ping @romainmenke given that he did the last push of code to this using max-color.

**Comment by romainmenke** [comment]
🤔 no idea what could trigger this.

If the polyfill fails in some way, CSS should still apply some colors (inherited or light mode) and not black.

Is there any system config for high contrast or another a11y related setting?
Are there any browser extensions that could interfere?

**Comment by romainmenke** [comment]
Somehow it looks similar to this issue :

https://github.com/csstools/postcss-preset-env/issues/125

That site doesn't have dark mode, and somehow those example code styles also get the black text.

**Comment by brianmaierjr** [comment]
@romainmenke I'm seeing it in incognito windows and also in Firefox where I have no plugins/extensions installed.

**Comment by Antonio-Laguna** [comment]
@brianmaierjr would you like to try this: https://github.com/csstools/postcss-preset-env/issues/192 ? 

If not I'll give it a whirl and get it deployed so you can test :)

**Comment by Antonio-Laguna** [comment]
@brianmaierjr gave it a go myself, can you test and let me know if it works for you?

**Comment by brianmaierjr** [comment]
@Antonio-Laguna I'm just seeing this... Sorry. Everything looks good!

**Comment by Antonio-Laguna** [comment]
Glad it’s working!
