### ISSUE TITLE
CSS vars wrapped with `<span class=css-var>`

### ISSUE THREAD

**Issue by bigandy** [csstools/cssdb#75]
![Screenshot 2022-01-14 at 15 58 17](https://user-images.githubusercontent.com/603328/149552490-cd58d8a8-43f6-4619-bb18-b5b5c367f6da.png)

**Comment by Antonio-Laguna** [comment]
@bigandy thanks for catching this! Will take a look shortly

**Comment by Antonio-Laguna** [comment]
@bigandy this has been pushed and fixed
