### ISSUE TITLE
Color Mode toggle has a confusing UX

### ISSUE THREAD

**Issue by bigandy** [csstools/cssdb#76]
I'm getting this bug on latest MacOS Chrome 97.0.4692.71 (Official Build) (x86_64)

https://user-images.githubusercontent.com/603328/149552759-1cc3d5d9-7ad3-4c9a-a44a-e00265f4de77.mov

**Comment by Antonio-Laguna** [comment]
@bigandy thanks for reporting this!

Luckily this is not a bug. It has 3 positions,

Dark, Auto, Light.

Auto is to use whatever system preference you have is set to.

**Comment by bigandy** [comment]
@Antonio-Laguna ah thanks. It's not super clear to me as a user that this is the case. Looks like a UI toggle (on/off). https://www.nngroup.com/articles/toggle-switch-guidelines/ I wonder what a good UI for three modes would look like?

**Comment by Antonio-Laguna** [comment]
@bigandy completely understand and I agree it's confusing, it's sort of a UX nightmare that we need to figure out

**Comment by WebMechanic** [comment]
Hi, just fell for this, too, but figured it out with some fiddling. There's just very little room between "auto" and the other states.
It might help if the toggle would be a tad wider to give all three states enough room or add icons inside the circle. 
The "auto" (middle) now looks like the switch is just "resting".

**Comment by romainmenke** [comment]
I agree that removing is best.

This feature is a remnant of a time when PostCSS plugins were created that worked together with client side JS polyfills.

This is no longer representative of the work we do so I think it is better to remove this.
